logging.level.org.springframework: INFO
logging.level.com.vasconcelos: TRACE

spring.jpa.hibernate.ddl-auto: none

server:
    servlet.context-path: /shoppingcart-api
    port: 8200

catalog.service.url: http://localhost:8100/catalog-api