INSERT INTO CART (CART_ID, STATUS) VALUES(1, 'Created');
INSERT INTO CART_ITEM (CART_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES(1, 2, 1, 5.10);
INSERT INTO CART_ITEM (CART_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES(1, 3, 2, 15.50);
INSERT INTO CART_ITEM (CART_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES(1, 4, 3, 53.99);

INSERT INTO CART (CART_ID, STATUS) VALUES(2, 'Presented');
INSERT INTO CART_ITEM (CART_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES(2, 2, 1, 5.10);

INSERT INTO CART (CART_ID, STATUS) VALUES(3, 'Submitted');
INSERT INTO CART_ITEM (CART_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES(3, 2, 5, 5.10);
INSERT INTO CART_ITEM (CART_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES(3, 3, 2, 15.50);
