CREATE TABLE CART(
  CART_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  STATUS VARCHAR(16),
  ORDER_ID BIGINT
);

CREATE TABLE CART_ITEM(
  CART_ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CART_ID BIGINT,
  PRODUCT_ID BIGINT,
  QUANTITY INTEGER,
  PRICE DECIMAL
);
